# Generated by Django 4.2.7 on 2026-06-26 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_otpverification_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='api.customer')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sparepart')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('customer', 'part')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.customer')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.sparepart')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('part', 'customer')},
            },
        ),
    ]
